name: CI Flask Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black

    - name: Verificar que Flask se importa (build)
      run: python -c "import flask"

    - name: Ejecutar pruebas unitarias
      run: pytest

    - name: Validar estilo con Flake8
      run: flake8 .

    - name: Validar formato con Black
      run: black --check .
